### PR TITLE
fix: state diff is empty

### PR DESCRIPTION
**Pull request by gzeoneth**
seems like a tenderly regression / api change
@mds1 @beruda @strahor-13

### CODE REVIEW

**Comment by beruda** [comment]
@gzeoneth Sorry about that! We were fixing an issue with State Diffs on Avalanche and accidentally introduced a bug. Should be good now 🙏

**Comment by mds1** [comment]
I was wondering if we still want this now that the tenderly bug is fixed—are there any types of proposals that would have no state changes? My concern was that if a similar bug is introduced in the future, the report indicates no state changes when in reality that isn't the case. 

I see you merged this in your fork though, so presumably you're supportive of keeping this anyway. And I think that's ok because a proposal's execution could result in event emission and no state diff

**Comment by gzeoneth** [comment]
> I was wondering if we still want this now that the tenderly bug is fixed—are there any types of proposals that would have no state changes? My concern was that if a similar bug is introduced in the future, the report indicates no state changes when in reality that isn't the case.
> 
> I see you merged this in your fork though, so presumably you're supportive of keeping this anyway. And I think that's ok because a proposal's execution could result in event emission and no state diff

I think its fine, it was also show a warning if there is no state diff.

**Comment by gzeoneth** [comment]
also specific to Arbitrum's usecase, we may use seatbelt to simulate retryable creation and execution, which may have no state diff if they do simple thing like a eth transfer only

**Review by mds1 — APPROVED** [review]

**Pull request merged**
